#!/bin/sh

# Copyright (c)2017, Alexander Baldeck <alex.bldck@gmail.com>
# Original idea: Copyright (c)2011, Axel Kohlmeyer <akohlmey@gmail.com>


dir=/opt/nvidia-fancontrol
smi=/usr/bin/nvidia-smi
set=/usr/bin/nvidia-settings

source /etc/default/nvidia-fancontrol

pciid=`lspci  | sed -n -e '/VGA compatib.*NVIDIA/s/^\(..\):\(..\).\(.\).*/printf "%d:%d:%d\\\\\\\\n" 0x\1 0x\2 0x\3;/p'`

display=0
for s in `eval ${pciid}`
do \
    cfg=`mktemp /tmp/xorg-XXXXXXXX.conf`
    sed -e s,@GPU_BUS_ID@,PCI:${s},    \
        -e s,@SET_GPU_DIR@,${dir}, \
        ${dir}/xorg.conf >> ${cfg}

    sh=`mktemp /tmp/nvidia-fancontrol-XXXXXXX.conf`
    sed -e s,@GPU_BUS_ID@,PCI:${s},\
        ${dir}/nvidia-fancontrol-x >> ${sh}
    chmod a+x ${sh}
    (xinit ${sh} &>/var/log/nvidia-fancontrol/${display}.log --  :${display} -once -config ${cfg} &>/dev/null &)
    let display="${display} + 1"
done
